# Generated by Django 5.1.4 on 2025-03-06 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categoria", "0001_initial"),
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="detalles_productos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField(max_length=400)),
                ("fecha_caducidad", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("contacto", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="categoria.categoria",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="detalles_producto",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="productos.detalles_productos",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="proveedor",
            field=models.ManyToManyField(blank=True, to="productos.proveedor"),
        ),
    ]
